# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a26864bbdca46a6afc9362e52e8213926c53417f8c71cf3a913656f27cb7de41ae92548badb5e813e4c156df6e7d1d20cf5e140656aef18c5bd499c89957dd71

test:
  secret_key_base: 1f7896611b5750b96dc5f437d67ee90f030e179afd2475f4f10797e92855567bbdcefff2aa1c020f53897fcb454164deea4a2af97050571864447e295aa86dac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
